#!/usr/bin/env ruby

require 'optparse'
require 'net/http'
require 'uri'

options = {
  :annotate => false,
  :exclude => []
}

optparse = OptionParser.new do |opts|
  opts.on('-a', '--annotate', "Annotate output URLs with response code") do |a|
    options[:annotate] = true
  end
  
  opts.on('--exclude xxx,yyy', Array, "Exclude URLs in the output responding with any of the given response codes") do |f|
    options[:exclude] = f
  end
  
  opts.on('--include xxx,yyy', Array, "Only inlcude URLs in the output responding with any of the given response codes") do |f|
    options[:include] = f
  end
end

optparse.parse!


@connections = {}

def get_conntection(uri)
  host = uri.host
  port = uri.port
  key = "#{host}#{port}"
  http = Net::HTTP.new(host, port)
  http.use_ssl = uri.scheme == 'https'
  @connections[key] ||= http
end

def get_code(url)
  uri = URI.parse(url)
  
  req = get_conntection(uri)
  req.request_head(uri.request_uri).code
end

ARGF.each_line do |line|
  begin
    code = get_code(line.strip)
  rescue URI::InvalidURIError
    if options[:annotate]
      puts 'INVALIDURL; ' + line
    end
    next
  rescue SocketError
    if options[:annotate]
      puts 'SOCKETERR; ' + line
    end
    next
  rescue Errno::ECONNRESET
    if options[:annotate]
      puts 'CONNRESET; ' + line
    end
    next
  rescue Errno::ECONNREFUSED
    if options[:annotate]
      puts 'CONNREFUSED; ' + line
    end
    next
  end
  
  if options[:exclude]
    next if options[:exclude].include? code
  end
  
  if options[:include]
    next unless options[:include].include? code
  end
  
  if options[:annotate]
    puts code + '; ' + line
  else
    puts line
  end
end
